services:
  mysql:
    image: mysql:8.0
    container_name: Give__link_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Give__link_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Give--link_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Give_link_php
    restart: always
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "8080:80"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
   laravel:
